services:
  cam0:
    build: .
    environment:
      DISPLAY: $DISPLAY
    command: roslaunch --wait camera.launch name:=right video_device:=/dev/video2
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./launch/camera.launch:/root/catkin_ws/camera.launch

  cam1:
    build: .
    environment:
      DISPLAY: $DISPLAY
    command: roslaunch --wait camera.launch name:=left video_device:=/dev/video4
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./launch/camera.launch:/root/catkin_ws/camera.launch

  node_killer:
    build: .
    command: python3 /scripts/node_killer.py
    network_mode: host
    volumes:
      - ./scripts:/scripts

  orb_slam2:
    build:
      context: ORB_SLAM2
    # https://stackoverflow.com/a/69505647
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    network_mode: "host"