services:
  cam0:
    build: .
    environment:
      DISPLAY: $DISPLAY
    command: roslaunch --wait camera.launch name:=cam0 video_device:=/dev/video2
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./launch/camera.launch:/root/catkin_ws/camera.launch

  node_killer:
    build: .
    command: python3 /scripts/node_killer.py
    volumes:
      - ./scripts:/scripts